/* Copyright 2025 Esri
 *
 * Licensed under the Apache License Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// import { PartialRootState } from './configureStore';

// import { initialMapState, MapState } from '@shared/store/Map/reducer';
import {
    getChangeCompareToolDataFromHashParams,
    getMapCenterFromHashParams,
    getTemporalCompositeToolDataFromHashParams,
} from '@shared/utils/url-hash-params';

import { PartialRootState } from '@shared/store/configureStore';
import { getPreloadedState4UI } from '@shared/store/UI/getPreloadedState';
import { getPreloadedState4Map } from '@shared/store/Map/getPreloadedState';
import { getPreloadedState4ImageryScenes } from '@shared/store/ImageryScene/getPreloadedState';
import { DisasterResponseRasterFunctionName } from '@shared/services/disaster-response/config';
import { getPreloadedState4DisasterResponseExplorer } from '@shared/store/DisasterResponse/getPreloadedState';
import { DisasterResponseEvent } from '@shared/store/DisasterResponse/reducer';
import {
    TemporalCompositeToolState,
    initialState4TemporalCompositeTool,
} from '@shared/store/TemporalCompositeTool/reducer';
import { getPreloadedState4ChangeCompareTool } from '@shared/store/ChangeCompareTool/getPreloadedState';
import {
    ChangeCompareToolState,
    initialChangeCompareToolState,
} from '@shared/store/ChangeCompareTool/reducer';

const getPreloadedTemporalCompositeToolState = (
    hashParams: URLSearchParams
): TemporalCompositeToolState => {
    const data = getTemporalCompositeToolDataFromHashParams(hashParams);
    const proloadedState: TemporalCompositeToolState = {
        ...initialState4TemporalCompositeTool,
        ...data,
    };

    return proloadedState;
};

const getPreloadedChangeCompareToolState = (hashParams: URLSearchParams) => {
    const changeCompareToolData =
        getChangeCompareToolDataFromHashParams(hashParams);

    const fullPixelValuesRange = [-255, 255]; // for DRX, the change compare layer is generated by doing minus operation between two grayscale rasters, so the pixel value range is from -255 to 255

    const preloadedState: ChangeCompareToolState = {
        ...initialChangeCompareToolState,
        selectedOption: '', // for DRX, we don't have spectral index or radar index options in the change compare tool, so we set selectedOption to an empty string
        fullPixelValuesRange,
        selectedRange:
            changeCompareToolData?.selectedRange || fullPixelValuesRange, // for DRX, we set the default selected range to be [-50, 50] since it's a reasonable range to capture most of the changes while excluding very minor changes that could be noise. Users can adjust the selected range based on their needs.
    };

    return preloadedState;
};

export const getPreloadedState4DRX = ({
    events,
}: {
    events: DisasterResponseEvent[];
}): PartialRootState => {
    const hashParams = new URLSearchParams(window.location.hash.slice(1));

    /**
     * Map location info that contains center and zoom info from URL Hash Params
     */
    const mapLocationFromHashParams = getMapCenterFromHashParams(hashParams);

    const defaultRasterFunction: DisasterResponseRasterFunctionName =
        'Natural Color for Visualization - DRA';

    const preloadedState4ImageryScenes = getPreloadedState4ImageryScenes(
        hashParams,
        undefined,
        defaultRasterFunction
    );

    return {
        Map: getPreloadedState4Map(hashParams, undefined),
        UI: getPreloadedState4UI(hashParams, undefined),
        ImageryScenes: {
            ...preloadedState4ImageryScenes,
            // override the mode to "find a scene" if the mode is "dynamic" since DRX only supports "find a scene" mode
            mode:
                preloadedState4ImageryScenes.mode === 'dynamic'
                    ? 'find a scene'
                    : preloadedState4ImageryScenes.mode,
            // for DRX, we want to use the main and secondary scenes for the temporal composite layer, so we set useTwoSceneComposite to true
            useTwoSceneComposite: true,
            // for DRX, we want to support both 'scene-to-scene' and 'scene-to-basemap' sub-modes in the swipe mode, so we set the availableSwipeSubModes to include both sub-modes
            availableSwipeSubModes: ['scene-to-scene', 'scene-to-basemap'],
        },
        DisasterResponseExplorer: getPreloadedState4DisasterResponseExplorer({
            hashParams,
            events,
        }),
        TemporalCompositeTool:
            getPreloadedTemporalCompositeToolState(hashParams),
        ChangeCompareTool: getPreloadedChangeCompareToolState(hashParams),
    };
};
